### ISSUE TITLE
codelite source archive has change

### ISSUE THREAD

**Issue by schmaller** [fusion809/sabayon-tools#2]
Please update manifest to the recent source archive.

diff --git a/dev-util/codelite/Manifest b/dev-util/codelite/Manifest
index 37db669..18c7e8a 100644
--- a/dev-util/codelite/Manifest
+++ b/dev-util/codelite/Manifest
@@ -1,3 +1,3 @@
 AUX codelite_dont_strip.patch 1255 SHA256 54fc41ec98e7909d8eb7846b02f0018ecc4ef228da037ec10971b165b31957d0 SHA512 543365ee0910d47f68fab11c8b1ce369f5ec8fbf8f2347556ad877f9cd53058f017a74d911d0c8a8010de944009ec8cccc0ec461201e062cef678b203e31a6a4 WHIRLPOOL 5f649b70ea9c59c6b99aea616f8ee114a140743dbd89502271adf01afeb886f9bf8063c2522318ef8e58a0ad33272d5d75a2e716c60844644b9dadcde5e4502c
-DIST codelite-9.2.tar.gz 72878710 SHA256 2e82e26d55e9884cd5c1061efd3ab4d8bd81dc6e095c5b811d0a3cba395e6118 SHA512 8788dad8fff2ae66827d754ad08a1a30429b3140d45c36d9da06935e72074ed8290cc6c1627bccf31511f4040456294538f34e593fd2adc6272f728ca88edb48 WHIRLPOOL 68ece16bab22b1f0d444934cc8ccbb97b92498538e61a884ea266d0ec457051e41c77a02ba1b4288121a9941f8869442b774f41f248083fc2c3033f5bc6f0264
+DIST codelite-9.2.tar.gz 92205408 SHA256 2e82e26d55e9884cd5c1061efd3ab4d8bd81dc6e095c5b811d0a3cba395e6118 SHA512 8788dad8fff2ae66827d754ad08a1a30429b3140d45c36d9da06935e72074ed8290cc6c1627bccf31511f4040456294538f34e593fd2adc6272f728ca88edb48 WHIRLPOOL 68ece16bab22b1f0d444934cc8ccbb97b92498538e61a884ea266d0ec457051e41c77a02ba1b4288121a9941f8869442b774f41f248083fc2c3033f5bc6f0264
 EBUILD codelite-9.2.ebuild 960 SHA256 74b05861dcd6800926598485b753912ac8afe10bd6ed32b07ca5b9a8c296ce2b SHA512 112610908327f91b942df0a1af9012c4772139d465f7349e087bc0032e3f6d2ce0b6ff7934527ac82e5b24872b2aaf17891ab399e1d1b811d353c44234598016 WHIRLPOOL 224e33bf9ee67e8ced7291fd361d13fb2246be5e6515b1e93c0ef472983ab2ae4be316a49a457e19654fd3b0f241f2be354535abcf93f28479348c20cca9b42b
l

**Comment by fusion809** [comment]
Done in commit [#8282280](https://github.com/fusion809/sabayon-tools/commit/8282280be93c9445f7caf340a6eaa2bafe90d37d).
